### ISSUE TITLE
Add  SENZING_ENGINE_CONFIGURATION_JSON  to tasks

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-ecs-poc-simple#110]
The `SENZING_ENGINE_CONFIGURATION_JSON` environment variable:

```yaml
          Environment:
            -
              Name: SENZING_ENGINE_CONFIGURATION_JSON
              Value: !GetAtt SsmParameterSenzingEngineConfigurationJson.Value
```

Needs to be added to the following ECS task definitions:

1. EcsTaskDefinitionApiServer
2. EcsTaskDefinitionSshd
3. EcsTaskDefinitionSshdMax
4. EcsTaskDefinitionXterm

For AWS, this issue needs to be propagated into:

1. https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic
2. https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-choices
3. https://github.com/Senzing/aws-cloudformation-ecs

For docker-compose, this issue needs to be propagated into:
1. https://github.com/Senzing/docker-compose-demo
