### ISSUE TITLE
Modify template to only specify INI information once

### ISSUE THREAD

**Issue by antaenc** [Senzing/aws-cloudformation-ecs-poc-simple#53]
Currently the ini parms are specified in 4 resource definitions, adding additional parms requires modifying it correctly in all locations. Define the ini string once and use mapping/sub in the yaml to introduce the string where required. This will simply times we or customers need to tweak the parms.

**Comment by docktermj** [comment]
Trying

```yaml
Mappings:
  Constants:
    Engine:
      Configuration: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "BACKEND": "HYBRID",
            "CONNECTION":"postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostCore}:${DatabasePortCore}:${DatabaseName}"
          },
          "C1": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostRes}:${DatabasePortRes}:${DatabaseName}"
          },
          "C2": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostLibfeat}:${DatabasePortLibfeat}:${DatabaseName}"
          },
          "HYBRID": {
            "LIB_FEAT": "C2",
            "LIB_FEAT_HKEY": "C2",
            "RES_FEAT": "C1",
            "RES_FEAT_EKEY": "C1",
            "RES_FEAT_LKEY": "C1",
            "RES_FEAT_STAT": "C1"
          }
        }
:
  EcsTaskDefinitionInitSenzing:
    Properties:
      ContainerDefinitions:
        -
          Environment:
            -
              Name: SENZING_ENGINE_CONFIGURATION_JSON
              Value: !Sub
                - !FindInMap [Constants, Engine, Configuration]
                - DatabaseHostLibfeat: !GetAtt RdsDbClusterLibfeat.Endpoint.Address
                  DatabaseHostCore: !GetAtt RdsDbClusterCore.Endpoint.Address
                  DatabaseHostRes: !GetAtt RdsDbClusterRes.Endpoint.Address
                  DatabaseName: !FindInMap [Constants, Database, Name]
                  DatabasePassword: !GetAtt LambdaRunnerDbPassword.RandomString
                  DatabasePortLibfeat: !GetAtt RdsDbClusterLibfeat.Endpoint.Port
                  DatabasePortCore: !GetAtt RdsDbClusterCore.Endpoint.Port
                  DatabasePortRes: !GetAtt RdsDbClusterRes.Endpoint.Port
                  DatabaseUsername: !FindInMap [Constants, Database, Username]        
```

Gives this error:

```
Template error: One or more Fn::Sub intrinsic functions don't specify expected arguments. Specify a string as first argument, and an optional second argument to specify a mapping of values to replace in the string
```

**Comment by docktermj** [comment]
I think this is the killer information:

> For the String parameter, you can't use any functions. You must specify a string value. 

So using `!FindInMap [Constants, Engine, Configuration]` won't work.

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w2ab1c33c28c59c13

**Comment by docktermj** [comment]
@antaenc I don't think it is possible given the current constraints of a Cloudformation template.

Here's the rationale:

1. The `SENZING_ENGINE_CONFIGURATION_JSON` variable needs information that is only available at runtime.  (e.g. Database hostnames, ports, usernames).  So these values must be substituted into the JSON after the databases have been allocated.  This is done using the Cloudformation `!Sub` function.
1. The Cloudformation `!Sub` function only supports a "string" template.  So there is no mechanism to support a function that returns a previously defined string.  (Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)

I've tested this using `Mappings:` (!FindInMap[]) and `Parameters:` (!Ref).   Neither mechanisms works because of the constraint on the `!Sub` template requirements.

Unless there's another approach, I'll have to close this issue as un-fixable.

**Comment by docktermj** [comment]
I've created an AWS Support Ticket to see if there's another approach that we haven't considered.

**Comment by docktermj** [comment]
AWS Support gave the following example of using `AWS::SSM::Parameter`

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  POC template that achieves the use case of specifying the ENV-VAR-JSON config. once - while it is used multiple times within the same
  template (inside AWS::ECS::TaskDefinition).

Resources:
  SSMParameter:
    Type: AWS::SSM::Parameter # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
    Properties:
      Name: SENZING_ENGINE_CONFIGURATION_JSON
      Type: String
      Value: !Sub
        - >-
          {
              "PIPELINE": {
                  "CONFIGPATH": "/etc/opt/senzing",
                  "RESOURCEPATH": "/opt/senzing/g2/resources",
                  "SUPPORTPATH": "/opt/senzing/data"
              },
              "SQL": {
                  "BACKEND": "HYBRID",
                  "CONNECTION":"postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostCore}:${DatabasePortCore}:${DatabaseName}"
              },
              "C1": {
                  "CLUSTER_SIZE": "1",
                  "DB_1": "postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostRes}:${DatabasePortRes}:${DatabaseName}"
              },
              "C2": {
                  "CLUSTER_SIZE": "1",
                  "DB_1": "postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseHostLibfeat}:${DatabasePortLibfeat}:${DatabaseName}"
              },
              "HYBRID": {
                  "LIB_FEAT": "C2",
                  "LIB_FEAT_HKEY": "C2",
                  "RES_FEAT": "C1",
                  "RES_FEAT_EKEY": "C1",
                  "RES_FEAT_LKEY": "C1",
                  "RES_FEAT_STAT": "C1"
              }
          }
        # Please note the dynamic variables within !Sub (DatabaseHostLibfeat, etc.) have static values set for simplication purposes
        # Your template definition of referencing values from other resources/parameters should work just as well
        - DatabaseHostLibfeat: RdsDbClusterLibfeat
          DatabaseHostCore: RdsDbClusterCore
          DatabaseHostRes: RdsDbClusterRes
          DatabaseName: Database
          DatabasePassword: LambdaRunnerDbPassword
          DatabasePortLibfeat: RdsDbClusterLibfeat
          DatabasePortCore: RdsDbClusterCore
          DatabasePortRes: RdsDbClusterRes
          DatabaseUsername: Database
      
  Task1Definition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: amazon/amazon-ecs-sample
          PortMappings:
            - ContainerPort: 12012
              Protocol: tcp
          Cpu: 256
          Memory: 512
          Name: container
          Environment:
            - Name: !Ref SSMParameter
              Value: !GetAtt SSMParameter.Value

  Task2Definition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: amazon/amazon-ecs-sample
          PortMappings:
            - ContainerPort: 21021
              Protocol: tcp
          Cpu: 512
          Memory: 1024
          Name: container
          Environment:
            - Name: !Ref SSMParameter
              Value: !GetAtt SSMParameter.Value
```
