### ISSUE TITLE
YAML edit

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/aws-cloudformation-ecs-poc-simple#83]
I have forked this repository and modified cloudformation.yaml but it won't deploy (what am I missing?) - see link
https://github.com/christianswanepoel/aws-cloudformation-ecs-poc-simple/commits/main/cloudformation.yaml

**Comment by docktermj** [comment]
@christianswanepoel Not sure what error(s) you are seeing, but you do need to be aware of acceptable AWS Aurora Postgress capacity values.  See
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-scalingconfiguration.html#cfn-rds-dbcluster-scalingconfiguration-mincapacity

**Comment by christianswanepoel** [comment]
(My favourite time of the day - when @docktermj goes online ;) )
See the error:
"Template format error: Unresolved resource dependencies [EcsServiceStreamLoader] in the Resources block of the template"

**Comment by docktermj** [comment]
Check your "DependsOn" clauses.

**Comment by christianswanepoel** [comment]
Ok I went back to basics
Downloaded and liked your vanilla cloudformation.yaml and it worked.
Then only edited lines 171 to 180  and it failed with same error.

  ```
  Run:
      ApiServer: Yes
      Jupyter: No
      Redoer: Yes
      Sshd: No
      StreamLoader: No
      Swagger: No
      VpcFlowLogs: No
      WebApp: No
      Xterm: No
```
